name: PR Review

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened
      - edited

env:
  LINTER_FILES_LIST: "*.yml *.yaml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: list dir
        run: |
          ls -la

      - name: Lint Pull Request
        run: yamllint --strict "$(git ls-files $LINTER_FILES_LIST --exclude-standard)"
