name: Terraform workflow
run-name: Terraform plan workflow
env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
on:
  push:
    branches:
      - main

on:
  workflow_dispatch

jobs:

  Terraform-Init:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - uses: actions/cache@v4
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: terraform-init-dir

      - name: Init
        id: init
        run: terraform init

      - run: ls -la

  Terraform-Plan:
    needs: Terraform-Init
    runs-on: ubuntu-latest
    steps:

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: terraform-init-dir

      - name: Plan
        id: plan
        run: terraform plan -input=false -no-color -out=terraform_plan.tfplan

      - uses: actions/cache@v4
        with:
          path: |
            .terraform
            .terraform.lock.hcl
            terraform_plan.tfplan
          key: terraform-init-dir

  Terraform-Apply:
    needs: Terraform-Plan
    environment:
      name: manual-approve
    runs-on: ubuntu-latest
    steps:

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        with:
          path: |
            .terraform
            .terraform.lock.hcl
            terraform_plan.tfplan
          key: terraform-init-dir

      - run: ls -la

      - name: Apply
        id: apply
        run: terraform apply -no-color -auto-approve terraform_plan.tfplan

